// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppPostgres.Models;

#nullable disable

namespace WebAppPostgres.Migrations
{
    [DbContext(typeof(FurnitureDBContext))]
    partial class FurnitureDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppPostgres.Models.Furniture", b =>
                {
                    b.Property<int>("FurnitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FurnitureId"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("FurnitureName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("FurnitureTypeID")
                        .HasColumnType("integer");

                    b.HasKey("FurnitureId");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("WebAppPostgres.Models.FurnitureType", b =>
                {
                    b.Property<int>("FurnitureTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FurnitureTypeID"));

                    b.Property<string>("FurnitureTypeName")
                        .HasColumnType("text");

                    b.HasKey("FurnitureTypeID");

                    b.ToTable("FurnitureType");
                });
#pragma warning restore 612, 618
        }
    }
}
